# ───────────────────────────────────────────────────────────
# Tell Netlify where to find our site & our Functions
# ───────────────────────────────────────────────────────────
[build]
  publish   = "."                  # our site lives in root
  functions = "netlify/functions"  # lambdas live here

# the redirect below makes
# /.netlify/functions/*  map to that folder at runtime
[[redirects]]
  from   = "/.netlify/functions/*"
  to     = "/.netlify/functions/:splat"
  status = 200

